import type { Metadata } from "next";
import { Pacifico, Gabarito, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "./sections/header";
import ScrollableList from "./components/scrollable-list";

const jetbrains_mono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrains_mono.variable} ${gabarito.variable} ${pacifico.variable} relative antialiased`}>
          <Header/>
          <div className="sticky top-0 w-full h-screen -mt-[50%] -z-50 bg-gradient-to-b from-black/10 to-black/20"></div>
          <div className="relative flex w-full min-h-screen">
            <ScrollableList/>
            <div className="flex w-full">
              {children}
            </div>
          </div>
      </body>
    </html>
  );
}
